Repository iabacus2024dev/backend, pull requests merged in 2025-03, with the labels that each got.

#75 [REQ-05-03][FUN-044] 협력사 등록 API 개발
  src/main/java/kr/co/iabacus/sales/core/common/error/ErrorCode.java
  src/main/java/kr/co/iabacus/sales/web/partners/controller/PartnersController.java
  src/main/java/kr/co/iabacus/sales/web/partners/dto/EmptyStringToNullEnumDeserializer.java
  src/main/java/kr/co/iabacus/sales/web/partners/dto/PartnersCreateRequest.java
  src/main/java/kr/co/iabacus/sales/web/partners/dto/PartnersSearchCondition.java
  src/main/java/kr/co/iabacus/sales/web/partners/repository/PartnersRepository.java
  src/main/java/kr/co/iabacus/sales/web/partners/service/PartnersService.java
  src/main/resources/errors.properties
Labels: ✨ Feature

#78 [REQ-07-08][FUN-070]투입인원 상세조회 API
  src/main/java/kr/co/iabacus/sales/core/common/error/ErrorCode.java
  src/main/java/kr/co/iabacus/sales/web/project/controller/ContractMemberController.java
  src/main/java/kr/co/iabacus/sales/web/project/dto/ContractMemberDetailResponse.java
  src/main/java/kr/co/iabacus/sales/web/project/dto/ContractMemberResponse.java
  src/main/java/kr/co/iabacus/sales/web/project/service/ContractMemberService.java
  src/main/resources/errors.properties
Labels: ✨ Feature

#80 [REQ-04-04][FUN-031] 구성원 등록 API 수정 사항 적용
  src/main/java/kr/co/iabacus/sales/web/member/dto/MemberRegisterRequest.java
  src/main/java/kr/co/iabacus/sales/web/member/service/MemberService.java
Labels: ✨ Feature

#84 [REQ-05-05][FUN-046]협력사 수정 API 개발
  src/main/java/kr/co/iabacus/sales/web/common/Address.java
  src/main/java/kr/co/iabacus/sales/web/partners/controller/PartnersController.java
  src/main/java/kr/co/iabacus/sales/web/partners/domain/Partners.java
  src/main/java/kr/co/iabacus/sales/web/partners/dto/PartnersUpdateRequest.java
  src/main/java/kr/co/iabacus/sales/web/partners/service/PartnersService.java
  src/main/resources/db/data.sql
Labels: ✨ Feature

#87 [REQ-04-04][FUN-031] 구성원 전체 조회 api
  src/main/java/kr/co/iabacus/sales/web/member/controller/MemberController.java
  src/main/java/kr/co/iabacus/sales/web/member/dto/MemberListResponse.java
  src/main/java/kr/co/iabacus/sales/web/member/dto/MemberSearchCondition.java
  src/main/java/kr/co/iabacus/sales/web/member/repository/MemberRepository.java
  src/main/java/kr/co/iabacus/sales/web/member/repository/MemberRepositoryCustom.java
  src/main/java/kr/co/iabacus/sales/web/member/repository/MemberRepositoryImpl.java
  src/main/java/kr/co/iabacus/sales/web/member/service/MemberService.java
Labels: ✨ Feature

#91 [REQ-04-10][FUN-092] 팀 등록을 위한 본부, 담당, 팀 조회 API
  src/main/java/kr/co/iabacus/sales/web/team/controller/TeamController.java
  src/main/java/kr/co/iabacus/sales/web/team/repository/TeamRepository.java
  src/main/java/kr/co/iabacus/sales/web/team/service/TeamService.java
Labels: ✨ Feature

#93 [REQ-04-07][FUN-035] 구성원 삭제 처리 API
  src/main/java/kr/co/iabacus/sales/web/member/controller/MemberController.java
  src/main/java/kr/co/iabacus/sales/web/member/service/MemberService.java
Labels: ✨ Feature

#88 [REQ-06-01][FUN-050] 프로젝트 조회 API
  src/main/java/kr/co/iabacus/sales/web/project/controller/ProjectController.java
  src/main/java/kr/co/iabacus/sales/web/project/domain/Project.java
  src/main/java/kr/co/iabacus/sales/web/project/dto/ProjectResponse.java
  src/main/java/kr/co/iabacus/sales/web/project/repository/ProjectRepository.java
  src/main/java/kr/co/iabacus/sales/web/project/service/ProjectService.java
Labels: ✨ Feature

#95 [REQ-04-08][FUN-037] 구성원 퇴사 처리 API
  src/main/java/kr/co/iabacus/sales/core/common/error/ErrorCode.java
  src/main/java/kr/co/iabacus/sales/web/member/controller/MemberController.java
  src/main/java/kr/co/iabacus/sales/web/member/domain/Member.java
  src/main/java/kr/co/iabacus/sales/web/member/dto/MemberDetailResponse.java
  src/main/java/kr/co/iabacus/sales/web/member/dto/MemberQuitRequest.java
  src/main/java/kr/co/iabacus/sales/web/member/service/MemberService.java
  src/main/resources/errors.properties
Labels: ✨ Feature

#100 [COMMON] 페이징 수정 및 동시 수정 검증 추가
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/pull_request_template.md
  src/main/java/com/iabacus/salespro/core/error/ErrorCode.java
  src/main/java/com/iabacus/salespro/web/common/PageResponse.java
  src/main/java/com/iabacus/salespro/web/employee/controller/EmployeeController.java
  src/main/java/com/iabacus/salespro/web/employee/request/EmployeeUpdateRequest.java
  src/main/java/com/iabacus/salespro/web/employee/response/EmployeeDetailResponse.java
  src/main/java/com/iabacus/salespro/web/employee/service/EmployeeService.java
  src/main/java/com/iabacus/salespro/web/partners/controller/PartnersController.java
  src/main/java/com/iabacus/salespro/web/partners/request/PartnersUpdateRequest.java
  src/main/java/com/iabacus/salespro/web/partners/response/PartnersDetailResponse.java
  src/main/java/com/iabacus/salespro/web/partners/response/PartnersSearchResponse.java
  src/main/java/com/iabacus/salespro/web/partners/service/PartnersService.java
  src/main/java/com/iabacus/salespro/web/project/controller/ProjectController.java
  src/main/java/com/iabacus/salespro/web/project/request/ProjectUpdateRequest.java
  src/main/java/com/iabacus/salespro/web/project/response/ProjectDetailResponse.java
  src/main/java/com/iabacus/salespro/web/project/service/ProjectService.java
  src/main/resources/common/paging.yml
  src/main/resources/errors.properties
Labels: ✨ Feature, 🪄 Fix, 🔨 Refactor

#102 [REQ-02-06][FUN-010/011] 로그인 계정 잠금 로직 추가
  src/main/java/com/iabacus/salespro/core/security/config/SecurityConfig.java
  src/main/java/com/iabacus/salespro/core/security/handler/CustomLoginFailHandler.java
  src/main/java/com/iabacus/salespro/core/security/handler/CustomLoginSuccessHandler.java
  src/main/java/com/iabacus/salespro/core/security/provider/CustomUserDetailsAuthenticationProvider.java
  src/main/java/com/iabacus/salespro/web/member/domain/Member.java
  src/main/resources/errors.properties
Labels: ✨ Feature

#103 [COMMON] 로그인 버그 수정
  src/main/java/com/iabacus/salespro/core/security/provider/CustomUserDetailsAuthenticationProvider.java
Labels: 🐞 BugFix

#105 feature: 로그인한 이용자의 권한 조회 API 및 phone 버그 수정
  src/main/java/com/iabacus/salespro/web/common/Phone.java
  src/main/java/com/iabacus/salespro/web/department/controller/DepartmentController.java
  src/main/java/com/iabacus/salespro/web/role/controller/RoleController.java
  src/main/java/com/iabacus/salespro/web/role/repository/RoleRepository.java
  src/main/java/com/iabacus/salespro/web/role/response/AuthorityResponse.java
  src/main/java/com/iabacus/salespro/web/role/service/RoleService.java
Labels: ✨ Feature

#107 [REQ-10-01][FUN-089] 엑셀 업로드, 다운로드 기능 (협력사)
  build.gradle
  src/main/java/com/iabacus/salespro/core/excel/annotation/ExcelColumn.java
  src/main/java/com/iabacus/salespro/core/excel/annotation/ExcelSheet.java
  src/main/java/com/iabacus/salespro/core/excel/dto/ExcelSheetData.java
  src/main/java/com/iabacus/salespro/core/excel/dto/ExcelSheetDataGroup.java
  src/main/java/com/iabacus/salespro/core/excel/factory/ExcelMetadataFactory.java
  src/main/java/com/iabacus/salespro/core/excel/file/BaseSXSSFExcelFile.java
  src/main/java/com/iabacus/salespro/core/excel/file/ExcelFile.java
  src/main/java/com/iabacus/salespro/core/excel/file/ExcelMetadata.java
  src/main/java/com/iabacus/salespro/core/excel/file/SXSSFExcelFile.java
  src/main/java/com/iabacus/salespro/core/excel/file/SXSSFMultiSheetExcelFile.java
  src/main/java/com/iabacus/salespro/core/excel/util/SuperClassReflectionUtils.java
  src/main/java/com/iabacus/salespro/web/department/controller/DepartmentController.java
  src/main/java/com/iabacus/salespro/web/partners/controller/PartnersController.java
  src/main/java/com/iabacus/salespro/web/partners/repository/CustomPartnersRepository.java
  src/main/java/com/iabacus/salespro/web/partners/repository/PartnersRepositoryImpl.java
  src/main/java/com/iabacus/salespro/web/partners/request/PartnersExcelRequest.java
  src/main/java/com/iabacus/salespro/web/partners/response/PartnersExcelResponse.java
  src/main/java/com/iabacus/salespro/web/partners/service/PartnersService.java
  src/main/java/com/iabacus/salespro/web/project/repository/ProjectRepository.java
Labels: ✨ Feature, ⚙ Setting

#109 [REQ-03-04][FUN-023] 로그인한 이용자의 권한 조회 로직 수정
  src/main/java/com/iabacus/salespro/core/excel/file/BaseSXSSFExcelFile.java
  src/main/java/com/iabacus/salespro/core/excel/util/SuperClassReflectionUtils.java
  src/main/java/com/iabacus/salespro/core/security/config/SecurityConfig.java
  src/main/java/com/iabacus/salespro/core/security/filter/CustomAuthorizationFilter.java
  src/main/java/com/iabacus/salespro/core/security/provider/CustomUserDetailsAuthenticationProvider.java
  src/main/java/com/iabacus/salespro/core/security/service/CustomUserDetailsService.java
  src/main/java/com/iabacus/salespro/web/common/PageResponse.java
  src/main/java/com/iabacus/salespro/web/common/Phone.java
  src/main/java/com/iabacus/salespro/web/member/controller/MemberController.java
  src/main/java/com/iabacus/salespro/web/member/response/MemberMyInfoResponse.java
  src/main/java/com/iabacus/salespro/web/member/service/MemberService.java
  src/main/java/com/iabacus/salespro/web/partners/controller/PartnersController.java
  src/main/java/com/iabacus/salespro/web/role/controller/RoleController.java
  src/main/java/com/iabacus/salespro/web/role/response/AuthorityResponse.java
  src/main/java/com/iabacus/salespro/web/role/service/RoleService.java
  src/test/java/com/iabacus/salespro/SalesProApplicationTests.java
  src/test/java/com/iabacus/salespro/web/auth/controller/AuthControllerTest.java
  src/test/java/com/iabacus/salespro/web/auth/validator/EmailValidatorTest.java
  src/test/java/com/iabacus/salespro/web/auth/validator/PasswordValidatorTest.java
Labels: ✨ Feature, 🪄 Fix

#112 [REQ-10-01][FUN-089] 엑셀 업로드 에러처리
  src/main/java/com/iabacus/salespro/core/error/ErrorCode.java
  src/main/java/com/iabacus/salespro/web/partners/controller/PartnersController.java
  src/main/java/com/iabacus/salespro/web/partners/controller/PartnersExcelController.java
  src/main/java/com/iabacus/salespro/web/partners/repository/PartnersRepositoryImpl.java
  src/main/java/com/iabacus/salespro/web/partners/service/PartnersService.java
  src/main/resources/errors.properties
Labels: ✨ Feature

#114 [REQ-03-04][FUN-023] 로그인한 이용자 조회 및 권한 조회 쿼리 수정
  src/main/java/com/iabacus/salespro/core/security/config/SecurityConfig.java
  src/main/java/com/iabacus/salespro/web/employee/controller/EmployeeController.java
  src/main/java/com/iabacus/salespro/web/employee/repository/CustomEmployeeRepository.java
  src/main/java/com/iabacus/salespro/web/employee/repository/EmployeeRepositoryImpl.java
  src/main/java/com/iabacus/salespro/web/employee/response/EmployeeDetailResponse.java
  src/main/java/com/iabacus/salespro/web/employee/response/EmployeeMyInfoResponse.java
  src/main/java/com/iabacus/salespro/web/employee/service/EmployeeService.java
  src/main/java/com/iabacus/salespro/web/member/service/MemberService.java
  src/main/java/com/iabacus/salespro/web/role/repository/RoleRepository.java
  src/main/java/com/iabacus/salespro/web/role/service/RoleService.java
  src/test/java/com/iabacus/salespro/web/employee/repository/EmployeeRepositoryImplTest.java
  src/test/java/com/iabacus/salespro/web/role/repository/RoleRepositoryTest.java
Labels: 🐞 BugFix

#119 [REQ-04-10][FUN-091] 조직도 API 구현
  src/main/java/com/iabacus/salespro/web/department/controller/DepartmentController.java
  src/main/java/com/iabacus/salespro/web/department/domain/Department.java
  src/main/java/com/iabacus/salespro/web/department/repository/DepartmentRepository.java
  src/main/java/com/iabacus/salespro/web/department/response/TreeViewResponse.java
  src/main/java/com/iabacus/salespro/web/department/service/DepartmentService.java
  src/main/java/com/iabacus/salespro/web/partners/validator/PartnersValidator.java
Labels: ✨ Feature

#120 [REQ-04-10][FUN-091] 조직도 조회 API 리팩토링
  src/main/java/com/iabacus/salespro/core/initdata/InitEmployeeMemberDepartmentRoleData.java
  src/main/java/com/iabacus/salespro/web/department/response/TreeViewResponse.java
  src/main/java/com/iabacus/salespro/web/department/service/DepartmentService.java
  src/main/java/com/iabacus/salespro/web/employee/repository/EmployeeRepository.java
Labels: 🔨 Refactor

#122 [REQ-03-03][FUN-16] 역할 조회 API 구현 및 테스트
  src/main/java/com/iabacus/salespro/core/initdata/InitEmployeeMemberDepartmentRoleData.java
  src/main/java/com/iabacus/salespro/web/role/controller/RoleController.java
  src/main/java/com/iabacus/salespro/web/role/domain/Role.java
  src/main/java/com/iabacus/salespro/web/role/domain/RoleAuthority.java
  src/main/java/com/iabacus/salespro/web/role/repository/CustomRoleRepository.java
  src/main/java/com/iabacus/salespro/web/role/repository/RoleRepository.java
  src/main/java/com/iabacus/salespro/web/role/repository/RoleRepositoryImpl.java
  src/main/java/com/iabacus/salespro/web/role/response/RoleResponse.java
  src/main/java/com/iabacus/salespro/web/role/service/RoleService.java
  src/test/java/com/iabacus/salespro/web/role/repository/RoleRepositoryTest.java
Labels: ✨ Feature

#123 [REQ-05-01][FUN-040] 협력사 조회 동적 정렬 추가
  src/main/java/com/iabacus/salespro/core/util/QuerydslUtils.java
  src/main/java/com/iabacus/salespro/web/partners/repository/PartnersRepositoryImpl.java
Labels: ✨ Feature

#125 [REQ-10-01][FUN-089] 엑셀 유틸 수정
  src/main/java/com/iabacus/salespro/core/excel/file/ExcelFile.java
  src/main/java/com/iabacus/salespro/core/excel/util/WorksheetUtil.java
  src/main/java/com/iabacus/salespro/core/initdata/InitProjectData.java
  src/main/java/com/iabacus/salespro/web/department/repository/DepartmentRepository.java
  src/main/java/com/iabacus/salespro/web/partners/service/PartnersService.java
  src/main/java/com/iabacus/salespro/web/project/controller/ProjectController.java
  src/main/java/com/iabacus/salespro/web/project/domain/Project.java
  src/main/java/com/iabacus/salespro/web/project/repository/ProjectRepositoryImpl.java
  src/main/java/com/iabacus/salespro/web/project/request/ProjectExcelRequest.java
  src/main/java/com/iabacus/salespro/web/project/request/ProjectSearchCondition.java
  src/main/java/com/iabacus/salespro/web/project/request/ProjectUpdateRequest.java
  src/main/java/com/iabacus/salespro/web/project/response/ProjectDetailResponse.java
  src/main/java/com/iabacus/salespro/web/project/service/ProjectService.java
Labels: 🪄 Fix

#126 [REQ-05-03][FUN-044] 협력사 등록 api 수정
  src/main/java/com/iabacus/salespro/web/partners/domain/PartnersGrade.java
  src/main/java/com/iabacus/salespro/web/partners/request/PartnersCreateRequest.java
Labels: 🪄 Fix

#127 feat: 팀 목표금액 컬럼 추가
  src/main/java/com/iabacus/salespro/web/aggregate/domain/MonthlyEmployeeCostAggregate.java
  src/main/java/com/iabacus/salespro/web/aggregate/service/SalesAggregateService.java
  src/main/java/com/iabacus/salespro/web/department/repository/TeamSalesGoalRepository.java
Labels: ✨ Feature

#130 feature: 팀 조회 API 구현
  src/main/java/com/iabacus/salespro/web/department/controller/DepartmentController.java
  src/main/java/com/iabacus/salespro/web/department/repository/DepartmentRepository.java
  src/main/java/com/iabacus/salespro/web/department/response/DepartmentResponse.java
  src/main/java/com/iabacus/salespro/web/department/service/DepartmentService.java
Labels: ✨ Feature
