Repository iabacus2024dev/backend, pull requests merged in 2025-02, with the labels that each got.

#1 Update README.md
  README.md
Labels: 📃 Docs

#3 [common] 프로젝트 생성 및 공통화 작업
  .gitattributes
  .github/ISSUE_TEMPLATE/issue-template.md
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/kr/co/iabacus/sales/SalesApplication.java
  src/main/java/kr/co/iabacus/sales/core/common/entity/BaseEntity.java
  src/main/java/kr/co/iabacus/sales/core/common/entity/BaseTimeEntity.java
  src/main/java/kr/co/iabacus/sales/core/common/error/ErrorResponse.java
  src/main/java/kr/co/iabacus/sales/core/common/error/advice/GlobalExceptionHandler.java
  src/main/java/kr/co/iabacus/sales/core/common/error/exception/BusinessException.java
  src/main/java/kr/co/iabacus/sales/core/common/error/exception/TestNotFoundException.java
  src/main/java/kr/co/iabacus/sales/core/config/db/QuerydslConfig.java
  src/main/java/kr/co/iabacus/sales/core/config/jpa/JpaAuditingConfig.java
  src/main/java/kr/co/iabacus/sales/core/config/log/P6SpyConfig.java
  src/main/java/kr/co/iabacus/sales/core/config/log/P6SpyEventListener.java
  src/main/java/kr/co/iabacus/sales/core/config/log/P6SpyFormatter.java
  src/main/java/kr/co/iabacus/sales/core/config/web/CorsConfig.java
  src/main/java/kr/co/iabacus/sales/web/common/Money.java
  src/main/java/kr/co/iabacus/sales/web/common/Phone.java
  src/main/java/kr/co/iabacus/sales/web/common/Ratio.java
  src/main/java/kr/co/iabacus/sales/web/common/converter/MoneyConverter.java
  src/main/java/kr/co/iabacus/sales/web/common/converter/PhoneConverter.java
  src/main/java/kr/co/iabacus/sales/web/common/converter/RatioConverter.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/main/resources/common/common.yml
  src/test/java/kr/co/iabacus/sales/SalesApplicationTests.java
Labels: ✨ Feature

#4 init project
  .gitattributes
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/pull_request_template.md
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  pull_request_template.md
  settings.gradle
  src/main/java/kr/co/iabacus/sales/SalesApplication.java
  src/main/java/kr/co/iabacus/sales/core/common/entity/BaseEntity.java
  src/main/java/kr/co/iabacus/sales/core/common/entity/BaseTimeEntity.java
  src/main/java/kr/co/iabacus/sales/core/common/error/ErrorResponse.java
  src/main/java/kr/co/iabacus/sales/core/common/error/advice/GlobalExceptionHandler.java
  src/main/java/kr/co/iabacus/sales/core/common/error/exception/BusinessException.java
  src/main/java/kr/co/iabacus/sales/core/common/error/exception/TestNotFoundException.java
  src/main/java/kr/co/iabacus/sales/core/config/db/QuerydslConfig.java
  src/main/java/kr/co/iabacus/sales/core/config/jpa/JpaAuditingConfig.java
  src/main/java/kr/co/iabacus/sales/core/config/log/P6SpyConfig.java
  src/main/java/kr/co/iabacus/sales/core/config/log/P6SpyEventListener.java
  src/main/java/kr/co/iabacus/sales/core/config/log/P6SpyFormatter.java
  src/main/java/kr/co/iabacus/sales/core/config/web/CorsConfig.java
  src/main/java/kr/co/iabacus/sales/web/common/Money.java
  src/main/java/kr/co/iabacus/sales/web/common/Phone.java
  src/main/java/kr/co/iabacus/sales/web/common/Ratio.java
  src/main/java/kr/co/iabacus/sales/web/common/converter/MoneyConverter.java
  src/main/java/kr/co/iabacus/sales/web/common/converter/PhoneConverter.java
  src/main/java/kr/co/iabacus/sales/web/common/converter/RatioConverter.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/main/resources/common/common.yml
  src/test/java/kr/co/iabacus/sales/SalesApplicationTests.java
Labels: ✨ Feature

#7 [COMMON] gradle 버전 다운그레이드
  gradle/wrapper/gradle-wrapper.properties
Labels: 🐞 BugFix

#17 [COMMON] 시스템/비즈니스 오류 메시지 분리
  .gitignore
  src/main/java/kr/co/iabacus/sales/core/common/error/ErrorCode.java
  src/main/java/kr/co/iabacus/sales/core/common/error/advice/GlobalExceptionHandler.java
  src/main/java/kr/co/iabacus/sales/core/common/error/exception/BusinessException.java
  src/main/java/kr/co/iabacus/sales/core/common/error/exception/TestNotFoundException.java
  src/main/java/kr/co/iabacus/sales/core/common/util/MessageUtil.java
  src/main/java/kr/co/iabacus/sales/core/config/message/MessageSourceConfig.java
  src/main/resources/errors.properties
Labels: ⚙ Setting

#19 [COMMON] MessageUtil 수정 및 에러처리 설명 주석
  src/main/java/kr/co/iabacus/sales/core/common/error/ErrorCode.java
  src/main/java/kr/co/iabacus/sales/core/common/error/exception/BusinessException.java
  src/main/java/kr/co/iabacus/sales/core/common/util/MessageUtil.java
  src/main/java/kr/co/iabacus/sales/core/config/message/MessageSourceConfig.java
Labels: ⚙ Setting

#23 [COMMON] Entity 설계
  src/main/java/kr/co/iabacus/sales/core/common/entity/BaseEntity.java
  src/main/java/kr/co/iabacus/sales/core/config/web/CorsConfig.java
  src/main/java/kr/co/iabacus/sales/web/common/Address.java
  src/main/java/kr/co/iabacus/sales/web/common/Money.java
  src/main/java/kr/co/iabacus/sales/web/common/Ratio.java
  src/main/java/kr/co/iabacus/sales/web/common/converter/RatioConverter.java
  src/main/java/kr/co/iabacus/sales/web/login/domain/LoginHistory.java
  src/main/java/kr/co/iabacus/sales/web/member/domain/Classification.java
  src/main/java/kr/co/iabacus/sales/web/member/domain/ClassificationCode.java
  src/main/java/kr/co/iabacus/sales/web/member/domain/Member.java
  src/main/java/kr/co/iabacus/sales/web/partners/domain/Partners.java
  src/main/java/kr/co/iabacus/sales/web/partners/domain/PartnersGrade.java
  src/main/java/kr/co/iabacus/sales/web/permission/domain/Permission.java
  src/main/java/kr/co/iabacus/sales/web/permission/domain/PermissionScope.java
  src/main/java/kr/co/iabacus/sales/web/project/domain/Contract.java
  src/main/java/kr/co/iabacus/sales/web/project/domain/ContractMember.java
  src/main/java/kr/co/iabacus/sales/web/project/domain/ContractStatus.java
  src/main/java/kr/co/iabacus/sales/web/project/domain/ContractType.java
  src/main/java/kr/co/iabacus/sales/web/project/domain/Project.java
  src/main/java/kr/co/iabacus/sales/web/project/domain/ProjectStatus.java
  src/main/java/kr/co/iabacus/sales/web/project/domain/ProjectType.java
  src/main/java/kr/co/iabacus/sales/web/role/domain/Role.java
  src/main/java/kr/co/iabacus/sales/web/role/domain/RolePermission.java
  src/main/java/kr/co/iabacus/sales/web/team/domain/Team.java
  src/main/java/kr/co/iabacus/sales/web/team/domain/TeamSalesGoal.java
Labels: ✨ Feature

#24 [COMMON] Entity 값타입 버그 수정
  src/main/java/kr/co/iabacus/sales/core/common/error/ErrorCode.java
  src/main/java/kr/co/iabacus/sales/web/common/Ratio.java
  src/main/java/kr/co/iabacus/sales/web/common/converter/MoneyConverter.java
  src/main/java/kr/co/iabacus/sales/web/member/domain/Member.java
  src/main/java/kr/co/iabacus/sales/web/partners/domain/Partners.java
  src/main/java/kr/co/iabacus/sales/web/project/domain/ContractMember.java
  src/main/java/kr/co/iabacus/sales/web/project/domain/Project.java
  src/main/java/kr/co/iabacus/sales/web/team/domain/TeamSalesGoal.java
Labels: 🐞 BugFix

#25 [COMMON] Entity 값 타입 속성 수정
  src/main/java/kr/co/iabacus/sales/web/partners/domain/Partners.java
Labels: 🐞 BugFix

#28 [COMMON] 초기 데이터 세팅
  src/main/resources/application-local.yml
  src/main/resources/data.sql
Labels: ⚙ Setting

#34 [COMMON] 메일링 시스템 구현
  src/main/java/kr/co/iabacus/sales/core/common/error/ErrorCode.java
  src/main/java/kr/co/iabacus/sales/web/mail/MailClient.java
  src/main/java/kr/co/iabacus/sales/web/mail/MailService.java
  src/main/resources/application.yml
  src/main/resources/common/auth.yml
  src/main/resources/common/mail.yml
Labels: ✨ Feature

#37 [REQ-02-01][FUN-004] 회원 등록 절차 구현
  src/main/java/kr/co/iabacus/sales/InitData.java
  src/main/java/kr/co/iabacus/sales/web/auth/controller/AuthController.java
  src/main/java/kr/co/iabacus/sales/web/auth/domain/Auth.java
  src/main/java/kr/co/iabacus/sales/web/auth/dto/MemberRegisterRequest.java
  src/main/java/kr/co/iabacus/sales/web/auth/dto/PasswordChangeRequest.java
  src/main/java/kr/co/iabacus/sales/web/auth/dto/PasswordInitializeRequest.java
  src/main/java/kr/co/iabacus/sales/web/auth/repository/AuthRepository.java
  src/main/java/kr/co/iabacus/sales/web/auth/service/AuthService.java
  src/main/java/kr/co/iabacus/sales/web/member/repository/MemberRepository.java
  src/main/resources/errors.properties
  src/test/java/kr/co/iabacus/sales/web/auth/controller/AuthControllerTest.java
  src/test/java/kr/co/iabacus/sales/web/auth/repository/AuthRepositoryTest.java
  src/test/java/kr/co/iabacus/sales/web/auth/service/AuthServiceTest.java
  src/test/java/kr/co/iabacus/sales/web/member/repository/MemberRepositoryTest.java
Labels: ✨ Feature

#41 [REQ-02-02][FUN-008] 비밀번호 유효성 및 이메일 검증
  src/main/java/kr/co/iabacus/sales/core/common/error/ErrorCode.java
  src/main/java/kr/co/iabacus/sales/web/auth/service/AuthService.java
  src/main/java/kr/co/iabacus/sales/web/auth/validator/PasswordValidator.java
  src/main/java/kr/co/iabacus/sales/web/auth/validator/RegisterValidator.java
  src/test/java/kr/co/iabacus/sales/web/auth/service/AuthServiceTest.java
  src/test/java/kr/co/iabacus/sales/web/auth/validator/PasswordValidatorTest.java
  src/test/java/kr/co/iabacus/sales/web/auth/validator/RegisterValidatorTest.java
Labels: ✨ Feature

#46 [REQ-02-03][FUN-015] 비밀번호 초기화 인증 정보 삭제 스케줄러
  .gitignore
  src/main/java/kr/co/iabacus/sales/InitData.java
  src/main/java/kr/co/iabacus/sales/SalesApplication.java
  src/main/java/kr/co/iabacus/sales/web/auth/repository/AuthRepository.java
  src/main/java/kr/co/iabacus/sales/web/auth/schedule/AuthDeleteScheduleTasks.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/db/data.sql
  src/test/java/kr/co/iabacus/sales/SalesApplicationTests.java
  src/test/java/kr/co/iabacus/sales/web/auth/repository/AuthRepositoryTest.java
Labels: ✨ Feature

#48 [REQ-02-08][FUN-014] 비밀번호 찾기
  src/main/java/kr/co/iabacus/sales/InitData.java
  src/main/java/kr/co/iabacus/sales/core/common/error/ErrorCode.java
  src/main/java/kr/co/iabacus/sales/web/auth/controller/AuthController.java
  src/main/java/kr/co/iabacus/sales/web/auth/dto/PasswordFindRequest.java
  src/main/java/kr/co/iabacus/sales/web/auth/service/AuthService.java
  src/main/java/kr/co/iabacus/sales/web/auth/validator/EmailValidator.java
  src/main/java/kr/co/iabacus/sales/web/auth/validator/RegisterValidator.java
  src/main/java/kr/co/iabacus/sales/web/member/domain/Member.java
  src/main/resources/errors.properties
  src/test/java/kr/co/iabacus/sales/web/auth/controller/AuthControllerTest.java
  src/test/java/kr/co/iabacus/sales/web/auth/service/AuthServiceTest.java
  src/test/java/kr/co/iabacus/sales/web/auth/validator/EmailValidatorTest.java
  src/test/java/kr/co/iabacus/sales/web/auth/validator/RegisterValidatorTest.java
Labels: ✨ Feature

#52 [COMMON] 메일 전송 비동기 처리 및 메일 메시지 수정
  src/main/java/kr/co/iabacus/sales/SalesApplication.java
  src/main/java/kr/co/iabacus/sales/core/common/error/ErrorCode.java
  src/main/java/kr/co/iabacus/sales/web/mail/MailClient.java
  src/main/java/kr/co/iabacus/sales/web/mail/MailService.java
Labels: ✨ Feature

#53 [REQ-04-03][FUN-028] 구성원 상세 조회 API
  src/main/java/kr/co/iabacus/sales/web/member/controller/ClassificationController.java
  src/main/java/kr/co/iabacus/sales/web/member/controller/MemberController.java
  src/main/java/kr/co/iabacus/sales/web/member/dto/MemberDetailResponse.java
  src/main/java/kr/co/iabacus/sales/web/member/repository/ClassificationRepository.java
  src/main/java/kr/co/iabacus/sales/web/member/repository/MemberRepository.java
  src/main/java/kr/co/iabacus/sales/web/member/service/ClassificationService.java
  src/main/java/kr/co/iabacus/sales/web/member/service/MemberService.java
  src/main/java/kr/co/iabacus/sales/web/team/controller/TeamController.java
  src/main/java/kr/co/iabacus/sales/web/team/repository/TeamRepository.java
  src/main/java/kr/co/iabacus/sales/web/team/service/TeamService.java
Labels: ✨ Feature

#55 [REQ-07-02][FUN-061] 계약 상세 조회 API
  src/main/java/kr/co/iabacus/sales/core/common/error/ErrorCode.java
  src/main/java/kr/co/iabacus/sales/web/project/controller/ContractController.java
  src/main/java/kr/co/iabacus/sales/web/project/domain/ContractStatus.java
  src/main/java/kr/co/iabacus/sales/web/project/domain/ContractType.java
  src/main/java/kr/co/iabacus/sales/web/project/domain/ProjectStatus.java
  src/main/java/kr/co/iabacus/sales/web/project/dto/ContractDetailResponse.java
  src/main/java/kr/co/iabacus/sales/web/project/repository/ContractRepository.java
  src/main/java/kr/co/iabacus/sales/web/project/service/ContractService.java
  src/main/resources/db/data.sql
  src/main/resources/errors.properties
Labels: ✨ Feature

#56 [REQ-04-04][FUN-031] 구성원 등록 API
  src/main/java/kr/co/iabacus/sales/core/common/error/ErrorCode.java
  src/main/java/kr/co/iabacus/sales/web/member/controller/MemberController.java
  src/main/java/kr/co/iabacus/sales/web/member/dto/MemberRegisterRequest.java
  src/main/java/kr/co/iabacus/sales/web/member/repository/MemberRepository.java
  src/main/java/kr/co/iabacus/sales/web/member/service/MemberService.java
  src/main/resources/errors.properties
Labels: ✨ Feature

#59 [REQ-07-06][FUN-067] 계약 삭제 처리 API
  src/main/java/kr/co/iabacus/sales/web/project/controller/ContractController.java
  src/main/java/kr/co/iabacus/sales/web/project/service/ContractService.java
Labels: ✨ Feature

#60 [REQ-06-03][FUN-054] 프로젝트 등록 API
  src/main/java/kr/co/iabacus/sales/web/project/controller/ProjectController.java
  src/main/java/kr/co/iabacus/sales/web/project/domain/Project.java
  src/main/java/kr/co/iabacus/sales/web/project/dto/ProjectCreateRequest.java
  src/main/java/kr/co/iabacus/sales/web/project/repository/ProjectRepository.java
  src/main/java/kr/co/iabacus/sales/web/project/service/ProjectService.java
Labels: ✨ Feature

#61 [REQ-07-06][FUN-067] 계약 삭제 처리 API
  src/main/java/kr/co/iabacus/sales/core/common/error/ErrorCode.java
  src/main/java/kr/co/iabacus/sales/web/project/service/ContractService.java
  src/main/resources/errors.properties
Labels: 🪄 Fix

#63 [REQ-04-10][FUN-091] 트리뷰에 넣을 조직원 조회 API
  src/main/java/kr/co/iabacus/sales/InitData.java
  src/main/java/kr/co/iabacus/sales/web/member/dto/MemberResponse.java
  src/main/java/kr/co/iabacus/sales/web/member/repository/MemberRepository.java
  src/main/java/kr/co/iabacus/sales/web/project/domain/Project.java
  src/main/java/kr/co/iabacus/sales/web/team/controller/TeamController.java
  src/main/java/kr/co/iabacus/sales/web/team/dto/TeamResponse.java
  src/main/java/kr/co/iabacus/sales/web/team/repository/TeamRepository.java
  src/main/java/kr/co/iabacus/sales/web/team/service/TeamService.java
  src/test/java/kr/co/iabacus/sales/web/team/service/TeamServiceTest.java
Labels: ✨ Feature

#64 [REQ-07-03][FUN-063] 계약 생성 API
  src/main/java/kr/co/iabacus/sales/core/config/web/CorsConfig.java
  src/main/java/kr/co/iabacus/sales/web/project/controller/ContractController.java
  src/main/java/kr/co/iabacus/sales/web/project/dto/ContractCreateRequest.java
  src/main/java/kr/co/iabacus/sales/web/project/repository/ContractRepository.java
  src/main/java/kr/co/iabacus/sales/web/project/repository/ProjectRepository.java
  src/main/java/kr/co/iabacus/sales/web/project/service/ContractService.java
  src/main/resources/db/data.sql
Labels: ✨ Feature

#70 [REQ-07-05][FUN-065] 계약 수정 API
  src/main/java/kr/co/iabacus/sales/web/project/controller/ContractController.java
  src/main/java/kr/co/iabacus/sales/web/project/domain/Contract.java
  src/main/java/kr/co/iabacus/sales/web/project/dto/ContractUpdateRequest.java
  src/main/java/kr/co/iabacus/sales/web/project/service/ContractService.java
Labels: ✨ Feature

#66 [REQ-05-02][FUN-042] 협력사 상세 조회 API 개발
  src/main/java/kr/co/iabacus/sales/core/common/error/ErrorCode.java
  src/main/java/kr/co/iabacus/sales/web/partners/controller/PartnersController.java
  src/main/java/kr/co/iabacus/sales/web/partners/dto/PartnersResponse.java
  src/main/java/kr/co/iabacus/sales/web/partners/repository/PartnersRepository.java
  src/main/java/kr/co/iabacus/sales/web/partners/service/PartnersService.java
  src/main/resources/db/data.sql
  src/main/resources/errors.properties
Labels: ✨ Feature

#72 [REQ-05-01][FUN-040] 협력사 조회 API 개발
  src/main/java/kr/co/iabacus/sales/web/partners/controller/PartnersController.java
  src/main/java/kr/co/iabacus/sales/web/partners/dto/PartnersSearchCondition.java
  src/main/java/kr/co/iabacus/sales/web/partners/repository/PartnersRepository.java
  src/main/java/kr/co/iabacus/sales/web/partners/repository/PartnersRepositoryCustom.java
  src/main/java/kr/co/iabacus/sales/web/partners/repository/PartnersRepositoryImpl.java
  src/main/java/kr/co/iabacus/sales/web/partners/service/PartnersService.java
Labels: ✨ Feature

#68 [REQ-07-07][FUN-068] 투입인원 조회 API
  src/main/java/kr/co/iabacus/sales/web/project/controller/ContractMemberController.java
  src/main/java/kr/co/iabacus/sales/web/project/dto/ContractMemberResponse.java
  src/main/java/kr/co/iabacus/sales/web/project/repository/ContractMemberRepository.java
  src/main/java/kr/co/iabacus/sales/web/project/service/ContractMemberService.java
  src/main/resources/common/mail.yml
Labels: ✨ Feature
