Repository iabacus2024dev/backend, pull requests merged in 2025-04, with the labels that each got.

#132 [COMMON] 구성원 엑셀 API 구현
  src/main/java/com/iabacus/salespro/core/error/GlobalExceptionHandler.java
  src/main/java/com/iabacus/salespro/core/initdata/InitEmployeeMemberDepartmentRoleData.java
  src/main/java/com/iabacus/salespro/web/department/controller/DepartmentController.java
  src/main/java/com/iabacus/salespro/web/department/repository/DepartmentRepository.java
  src/main/java/com/iabacus/salespro/web/department/response/DepartmentResponse.java
  src/main/java/com/iabacus/salespro/web/department/service/DepartmentService.java
  src/main/java/com/iabacus/salespro/web/employee/controller/EmployeeController.java
  src/main/java/com/iabacus/salespro/web/employee/controller/EmployeeExcelController.java
  src/main/java/com/iabacus/salespro/web/employee/domain/Employee.java
  src/main/java/com/iabacus/salespro/web/employee/repository/CustomEmployeeRepository.java
  src/main/java/com/iabacus/salespro/web/employee/repository/EmployeeRepositoryImpl.java
  src/main/java/com/iabacus/salespro/web/employee/request/EmployeeCreateRequest.java
  src/main/java/com/iabacus/salespro/web/employee/request/EmployeeExcelRequest.java
  src/main/java/com/iabacus/salespro/web/employee/response/EmployeeDetailResponse.java
  src/main/java/com/iabacus/salespro/web/employee/response/EmployeeExcelResponse.java
  src/main/java/com/iabacus/salespro/web/employee/response/EmployeeSearchResponse.java
  src/main/java/com/iabacus/salespro/web/employee/service/EmployeeService.java
  src/main/java/com/iabacus/salespro/web/partners/domain/Partners.java
  src/main/java/com/iabacus/salespro/web/project/domain/Project.java
  src/main/java/com/iabacus/salespro/web/project/request/ProjectUpdateRequest.java
  src/main/java/com/iabacus/salespro/web/project/response/ProjectDetailResponse.java
  src/main/resources/errors.properties
  src/test/java/com/iabacus/salespro/web/aggregate/service/SalesAggregateServiceTest.java
  src/test/java/com/iabacus/salespro/web/auth/controller/AuthControllerTest.java
  src/test/java/com/iabacus/salespro/web/employee/repository/EmployeeRepositoryImplTest.java
Labels: ✨ Feature

#133 [REQ-08-02][FUN-078] 매출 장표 조회 API
  src/main/java/com/iabacus/salespro/web/aggregate/controller/AggregateController.java
  src/main/java/com/iabacus/salespro/web/aggregate/domain/MonthlyEmployeeCostAggregate.java
  src/main/java/com/iabacus/salespro/web/aggregate/repository/AggregateRepositoryCustom.java
  src/main/java/com/iabacus/salespro/web/aggregate/repository/AggregateRepositoryImpl.java
  src/main/java/com/iabacus/salespro/web/aggregate/response/AggregateResponse.java
  src/main/java/com/iabacus/salespro/web/aggregate/service/AggregateService.java
  src/main/java/com/iabacus/salespro/web/role/domain/AuthorityPage.java
Labels: ✨ Feature

#135 [REQ-04-08][FUN-037] 구성원 퇴사처리 API
  src/main/java/com/iabacus/salespro/web/employee/controller/EmployeeController.java
  src/main/java/com/iabacus/salespro/web/employee/request/EmployeeLeaveRequest.java
  src/main/java/com/iabacus/salespro/web/employee/service/EmployeeService.java
Labels: ✨ Feature

#136 [REQ-10-01][FUN-089] 엑셀 업로드 검증 로직 추가
  src/main/java/com/iabacus/salespro/core/error/GlobalExceptionHandler.java
  src/main/java/com/iabacus/salespro/core/initdata/InitEmployeeMemberDepartmentRoleData.java
  src/main/java/com/iabacus/salespro/web/employee/controller/EmployeeExcelController.java
  src/main/java/com/iabacus/salespro/web/employee/request/EmployeeExcelRequest.java
  src/main/java/com/iabacus/salespro/web/employee/request/EmployeeUpdateRequest.java
  src/main/java/com/iabacus/salespro/web/employee/service/EmployeeExcelService.java
  src/main/java/com/iabacus/salespro/web/employee/service/EmployeeService.java
  src/main/java/com/iabacus/salespro/web/employee/validator/EmployeeExcelValidator.java
  src/main/java/com/iabacus/salespro/web/partners/controller/PartnersExcelController.java
  src/main/java/com/iabacus/salespro/web/partners/repository/PartnersRepository.java
  src/main/java/com/iabacus/salespro/web/partners/request/PartnersExcelRequest.java
  src/main/java/com/iabacus/salespro/web/partners/request/PartnersUpdateRequest.java
  src/main/java/com/iabacus/salespro/web/partners/service/PartnersExcelService.java
  src/main/java/com/iabacus/salespro/web/partners/service/PartnersService.java
  src/main/java/com/iabacus/salespro/web/partners/validator/PartnersExcelValidator.java
  src/main/java/com/iabacus/salespro/web/project/controller/ProjectExcelController.java
  src/main/java/com/iabacus/salespro/web/project/request/ProjectUpdateRequest.java
  src/main/java/com/iabacus/salespro/web/project/service/ProjectExcelService.java
  src/main/java/com/iabacus/salespro/web/project/service/ProjectService.java
  src/main/java/com/iabacus/salespro/web/project/validator/ProjectExcelValidator.java
  src/main/resources/errors.properties
  src/test/java/com/iabacus/salespro/web/auth/controller/AuthControllerTest.java
Labels: ✨ Feature

#142 [REQ-08-02][FUN-078] 매출 장표 조회 API
  src/main/java/com/iabacus/salespro/web/aggregate/controller/AggregateController.java
  src/main/java/com/iabacus/salespro/web/aggregate/domain/Aggregate.java
  src/main/java/com/iabacus/salespro/web/aggregate/repository/AggregateRepositoryCustom.java
  src/main/java/com/iabacus/salespro/web/aggregate/repository/AggregateRepositoryCustomImpl.java
  src/main/java/com/iabacus/salespro/web/aggregate/response/AggregateResponse.java
  src/main/java/com/iabacus/salespro/web/aggregate/service/AggregateService.java
Labels: ✨ Feature

#144 feature: 전화번호 처리 유틸리티 도입 및 관련 로직 통합
  src/main/java/com/iabacus/salespro/web/common/Phone.java
  src/main/java/com/iabacus/salespro/web/partners/response/PartnersDetailResponse.java
  src/main/java/com/iabacus/salespro/web/partners/response/PartnersExcelResponse.java
  src/main/java/com/iabacus/salespro/web/partners/response/PartnersSearchResponse.java
  src/main/java/com/iabacus/salespro/web/project/response/ProjectDetailResponse.java
Labels: 🔨 Refactor

#147 feature: 직원 이메일 및 전화번호 유효성 검증 로직 추가
  src/main/java/com/iabacus/salespro/core/error/ErrorCode.java
  src/main/java/com/iabacus/salespro/web/aggregate/domain/Aggregate.java
  src/main/java/com/iabacus/salespro/web/aggregate/repository/AggregateRepositoryCustomImpl.java
  src/main/java/com/iabacus/salespro/web/aggregate/response/AggregateResponse.java
  src/main/java/com/iabacus/salespro/web/employee/repository/EmployeeRepository.java
  src/main/java/com/iabacus/salespro/web/employee/service/EmployeeService.java
  src/main/java/com/iabacus/salespro/web/employee/validator/EmployeeValidator.java
  src/main/resources/errors.properties
  src/test/java/com/iabacus/salespro/web/aggregate/response/AggregateResponseTest.java
  src/test/java/com/iabacus/salespro/web/aggregate/service/SalesAggregateServiceTest.java
Labels: ✨ Feature, 🪄 Fix

#149 fix: Querydsl 페이징 적용 코드 제거
  src/main/java/com/iabacus/salespro/web/employee/repository/EmployeeRepositoryImpl.java
Labels: 🐞 BugFix
